title: Elite Dangerous – Guardian Ruins
description: Guardian Ruins
remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

accent_color: "#00d4ff"         
link_color: "#66e0ff"
visited_link_color: "#33ccff"

show_downloads: false
show_footer: true

encoding: UTF-8
